name: Release to NuGet

on:
  push:
    tags: [ 'v*' ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore src/SuperUaePass/SuperUaePass.csproj
      
    - name: Build
      run: dotnet build src/SuperUaePass/SuperUaePass.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Pack
      run: dotnet pack src/SuperUaePass/SuperUaePass.csproj --no-build --configuration Release --output ./nupkgs
      
    - name: Publish to NuGet
      run: dotnet nuget push "./nupkgs/SuperUaePass.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's New in ${{ github.ref }}
          
          ### Enhanced Documentation
          - Comprehensive prerequisites for UAE Pass integration
          - Multiple usage examples (configuration-based, hardcoded, custom sections)
          - Complete Program.cs examples with session configuration
          - Troubleshooting guide with common issues and solutions
          - Security best practices and considerations
          
          ### Features
          - Support for all .NET versions (6.0, 7.0, 8.0, 9.0)
          - OAuth 2.0 authentication with UAE Pass
          - User profile retrieval and validation
          - Proxy support for enterprise environments
          - Comprehensive error handling
          
          ### Installation
          ```bash
          dotnet add package SuperUaePass
          ```
          
          ### Quick Start
          ```csharp
          // Program.cs
          builder.Services.AddSuperUaePass(builder.Configuration);
          ```
          
          For detailed documentation, visit the [GitHub repository](https://github.com/esamelzain/SuperUaePass).
        draft: false
        prerelease: false
